[package]
name = "boel"
version = "0.1.0"
edition = "2021"
authors = ["ucyo <cayoglu@me.com>"]
default-run = "boel"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.*"
byteorder = "1.4.*"
clap = "2.34.*"
env_logger = "0.9.*"
log = "0.4.*"
rand = "0.8.*"
rand_distr = "0.4.*"

[dev-dependencies]
criterion = "0.3.*"
iai = "0.1.*"

[[bin]]
name = "boel"
path = "bin/cli.rs"

[[bin]]
name = "rand"
path = "bin/rand.rs"
